# Generated by Django 5.0.4 on 2024-09-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroommatemodel',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='our_expense.addroommatemodel')),
            ],
        ),
    ]
