# Generated by Django 5.0.4 on 2024-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0002_alter_addroommatemodel_phone_expensemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUB_BillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Previous_EB_Date', models.DateField()),
                ('Previous_month_EB_Total_Reading', models.IntegerField()),
                ('Current_EB_Date', models.DateField()),
                ('Current_month_EB_Total_Reading', models.IntegerField()),
                ('EB_Unit_Cost', models.IntegerField()),
                ('Refuse_Removal_Amount', models.IntegerField()),
                ('Water_Utility_Amount', models.IntegerField()),
                ('GST', models.IntegerField()),
            ],
        ),
    ]
