# Generated by Django 5.0.4 on 2024-09-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0005_alter_pub_billmodel_current_month_eb_total_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub_billmodel',
            name='Water_Utility_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
