# Generated by Django 5.0.4 on 2024-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0006_pub_billmodel_water_utility_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub_billmodel',
            name='Current_EB_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
