# Generated by Django 5.0.4 on 2024-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0007_alter_pub_billmodel_current_eb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub_billmodel',
            name='Current_EB_Date',
            field=models.DateField(null=True),
        ),
    ]
