# Generated by Django 5.0.4 on 2024-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0010_pub_billmodel_total_units_pub_billmodel_total_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub_billmodel',
            name='Merge_Food_Expense_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
