# Generated by Django 5.0.4 on 2024-09-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_expense', '0011_pub_billmodel_merge_food_expense_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub_billmodel',
            name='Merge_Food_Expense_Date',
        ),
    ]
